import React from 'react';
import { Divider, Row, Col, Button } from 'antd';

const SceneComponent = () => {
    return (
        <div style={{minHeight: 'calc(70vh - 64px)'}}>
            <Divider orientation="left" orientationMargin="0">Scene</Divider>
            
            <Row>
                <Col span={12}>
                    <p>Scene generated by InstantNGP</p>
                </Col>
                <Col span={12}>
                    <Button type="default" block style={{marginTop: '12px'}}>Adjust Scene</Button>
                </Col>
            </Row>
            <Row style={{marginTop: '12px'}}>
                <canvas id="scene" style={{width: '100%', height: '100%', border: '1px solid #f0f0f0'}}></canvas>
            </Row>

        </div>  
    );
}

export default SceneComponent;