import { join } from "path";

export const runModelsConfigs = [
	{
		modelId: "instant-ngp",
		displayName: "Instant-NGP",
		dockerImage: "dromni/nerfstudio",
		installCmd: ["docker", "pull", "dromni/nerfstudio:1.0.0"],
		runCmdFn: (datasetId, datasetType) => [
			"docker",
			"run",
			"--gpus",
			"all",
			"-v",
			`${process.env.ROOT_DIR}/tmp/instant-ngp/:/workspace/`,
			"--rm",
			"--shm-size=12gb",
			"dromni/nerfstudio:1.0.0",
			"ns-train",
			"instant-ngp",
			"--timestamp",
			"latest",
			"--viewer.quit-on-train-completion",
			"True",
			"--data",
			`/workspace/data/${datasetId}`,
			datasetType
		],
		exportCmdFn: (datasetId) => [
			"docker",
			"run",
			"--gpus",
			"all",
			"-v",
			`${process.env.ROOT_DIR}/tmp/instant-ngp/:/workspace/`,
			"--rm",
			"--shm-size=12gb",
			"dromni/nerfstudio:1.0.0",
			"ns-export",
			"tsdf",
			"--load-config",
			`outputs/${datasetId}/instant-ngp/latest/config.yml`,
			"--output-dir",
			process.env.MESH_RESULTS_DIR_NAME,
		]
	},
	{
		modelId: "nerfacto",
		displayName: "Nerfacto",
		dockerImage: "dromni/nerfstudio",
		installCmd: ["docker", "pull", "dromni/nerfstudio:1.0.0"],
		runCmdFn: (datasetId, datasetType) => [
			"docker",
			"run",
			"--gpus",
			"all",
			"-v",
			`${process.env.ROOT_DIR}/tmp/nerfacto/:/workspace/`,
			"--rm",
			"--shm-size=12gb",
			"dromni/nerfstudio:1.0.0",
			"ns-train",
			"nerfacto",
			"--pipeline.model.predict-normals",
			"True",
			"--max-num-iterations",
			"500",
			"--viewer.quit-on-train-completion",
			"True",
			"--timestamp",
			"latest",
			"--data",
			`/workspace/data/${datasetId}`,
			datasetType
		],
		exportCmdFn: (datasetId) => [
			"docker",
			"run",
			"--gpus",
			"all",
			"-v",
			`${process.env.ROOT_DIR}/tmp/nerfacto/:/workspace/`,
			"--rm",
			"--shm-size=12gb",
			"dromni/nerfstudio:1.0.0",
			"ns-export",
			"poisson",
			"--load-config",
			`outputs/${datasetId}/nerfacto/latest/config.yml`,
			"--output-dir",
			process.env.MESH_RESULTS_DIR_NAME,
		],
	},
	{
		modelId: "kplanes",
		displayName: "K-Planes",
		dockerImage: "cloudnerf/kplanes",
		installCmd: [
			"docker",
			"build",
			"-t",
			"cloudnerf/kplanes",
			"-",
			"<",
			join(process.env.ROOT_DIR, "/run_models/dockerfiles/Dockerfile.kplanes"),
		],
		runCmdFn: (datasetId, datasetType) => [
			"docker",
			"run",
			"--gpus",
			"all",
			"-v",
			`${process.env.ROOT_DIR}/tmp/kplanes/:/workspace/`,
			"--rm",
			"--shm-size=12gb",
			"cloudnerf/kplanes",
			"ns-train",
			"kplanes",
			"--timestamp",
			"latest",
			"--viewer.quit-on-train-completion",
			"True",
			"--max-num-iterations",
			"500",
			"--data",
			`/workspace/data/${datasetId}`,
			datasetType,
		],
	},
];
