export const runModelsConfigs = [
	{
		modelId: "instantngp",
		displayName: "Instant-NGP",
		dockerImage: "dromni/nerfstudio",
		installCmd: "docker",
		installCmdArgs: ["run", "--rm", "dromni/nerfstudio:1.0.0", "ls"],
		runCmd: "docker",
		runCmdArgs: [
			"run",
			"--gpus",
			"all",
			"-v",
			`${process.env.ROOT_DIR}/tmp/instantngp/:/workspace/`,
			"--rm",
			"--shm-size=12gb",
			"dromni/nerfstudio:1.0.0",
			"ns-train",
			"instant-ngp",
			"--data",
			"/workspace/data",
		],
	},
	{
		modelId: "neus",
		displayName: "Neus",
		dockerImage: "dromni/nerfstudio",
		installCmd: "",
		runCmd: "docker",
		runCmdArgs: [
			"run",
			"--gpus",
			"all",
			"-v",
			`${process.env.ROOT_DIR}/tmp/neus/:/workspace/`,
			"--rm",
			"--shm-size=12gb",
			"dromni/nerfstudio:1.0.0",
			"ns-train",
			"neus",
			"--data",
			"/workspace/data",
		],
	},
	{
		modelId: "nerfacto",
		displayName: "Nerfacto",
		dockerImage: "dromni/nerfstudio",
		installCmd: "",
		runCmd: "docker",
		runCmdArgs: [
			"run",
			"--gpus",
			"all",
			"-v",
			`${process.env.ROOT_DIR}/tmp/nerfacto/:/workspace/`,
			"--rm",
			"--shm-size=12gb",
			"dromni/nerfstudio:1.0.0",
			"ns-train",
			"nerfacto",
			"--data",
			"/workspace/data",
		],
	},
	{
		modelId: "mipnerf",
		displayName: "Mip-NeRF",
		dockerImage: "dromni/nerfstudio",
		installCmd: "",
		runCmd: "docker",
		runCmdArgs: [
			"run",
			"--gpus",
			"all",
			"-v",
			`${process.env.ROOT_DIR}/tmp/mipnerf/:/workspace/`,
			"--rm",
			"--shm-size=12gb",
			"dromni/nerfstudio:1.0.0",
			"ns-train",
			"mipnerf",
			"--data",
			"/workspace/data",
		],
	},
	{
		modelId: "kplanes",
		displayName: "K-Planes",
		dockerImage: "cloudnerf/kplanes",
		installCmd: "",
		runCmd: "docker",
		runCmdArgs: [
			"run",
			"--gpus",
			"all",
			"-v",
			`${process.env.ROOT_DIR}/tmp/kplanes/:/workspace/`,
			"--rm",
			"--shm-size=12gb",
			"dromni/nerfstudio:1.0.0",
			"ns-train",
			"kplanes",
			"--data",
			"/workspace/data",
		],
	},
	{
		modelId: "kplanes-dynamic",
		displayName: "K-Planes (for dynamic scenes)",
		dockerImage: "cloudnerf/kplanes",
		installCmd: "",
		runCmd: "docker",
		runCmdArgs: [
			"run",
			"--gpus",
			"all",
			"-v",
			`${process.env.ROOT_DIR}/tmp/kplanes-dynamic/:/workspace/`,
			"--rm",
			"--shm-size=12gb",
			"dromni/nerfstudio:1.0.0",
			"ns-train",
			"kplanes-dynamic",
			"--data",
			"/workspace/data",
		],
	},
];
