version: '3.8'

services:
  nextjs:
    container_name: cloudnerf-nextjs
    build: 
      context: ./.devcontainer
      dockerfile: Dockerfile

    volumes:
      - ..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # AS SOON AS WE SETUP SUPABASE
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:supabase_database

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)